# Generated by Django 3.2.15 on 2023-08-08 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anagrafica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30, null=True)),
                ('cognome', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Anagrafica',
                'verbose_name_plural': 'Anagrafiche',
            },
        ),
        migrations.CreateModel(
            name='Approvvi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(blank=True, max_length=5, null=True)),
                ('descrizione', models.CharField(blank=True, max_length=20, null=True)),
                ('famiglia', models.CharField(blank=True, max_length=4, null=True)),
                ('fornitore', models.CharField(blank=True, max_length=30, null=True)),
                ('lt_gg', models.IntegerField(blank=True, null=True)),
                ('lt_week', models.IntegerField(blank=True, null=True)),
                ('soglia_approvvi', models.IntegerField(blank=True, default=4, null=True)),
                ('vincoli_di_fornitura', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'Approvvigionamento',
                'verbose_name_plural': 'Approvvigionamenti',
            },
        ),
        migrations.CreateModel(
            name='Articoli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ditta', models.DecimalField(decimal_places=0, default=1, max_digits=5)),
                ('codice', models.CharField(blank=True, max_length=25, null=True)),
                ('descrizione', models.CharField(blank=True, max_length=72, null=True)),
                ('descrizione_estesa', models.CharField(blank=True, max_length=1672, null=True)),
                ('codice_interno', models.CharField(blank=True, max_length=1672, null=True)),
                ('famiglia', models.CharField(blank=True, max_length=4, null=True)),
                ('descrizione_famiglia', models.CharField(blank=True, max_length=30, null=True)),
                ('sottofamiglia', models.CharField(blank=True, max_length=4, null=True)),
                ('descrizione_sottofamiglia', models.CharField(blank=True, max_length=30, null=True)),
                ('marca', models.CharField(blank=True, max_length=12, null=True)),
                ('descrizione_marca', models.CharField(blank=True, max_length=30, null=True)),
                ('gruppo_statistico_1', models.CharField(blank=True, max_length=4, null=True)),
                ('descrizione_grstat_1', models.CharField(blank=True, max_length=4, null=True)),
                ('gruppo_statistico_2', models.CharField(blank=True, max_length=4, null=True)),
                ('descrizione_grstat_2', models.CharField(blank=True, max_length=30, null=True)),
                ('gruppo_statistico_3', models.CharField(blank=True, max_length=4, null=True)),
                ('descrizione_grstat_3', models.CharField(blank=True, max_length=30, null=True)),
                ('gruppo_statistico_4', models.CharField(blank=True, max_length=4, null=True)),
                ('descrizione_grstat_4', models.CharField(blank=True, max_length=30, null=True)),
                ('deposito_scorte', models.CharField(blank=True, max_length=2, null=True)),
                ('descrizione_deposito_scorte', models.CharField(blank=True, max_length=40, null=True)),
                ('indice_scorte_fabbisogno', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('scorta_minima', models.IntegerField(blank=True, null=True)),
                ('scorta_massima', models.IntegerField(blank=True, null=True)),
                ('livello_riordino', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
            ],
            options={
                'verbose_name': 'Articolo',
                'verbose_name_plural': 'Articoli',
            },
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Auto',
                'verbose_name_plural': 'Auto',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_deposito', models.CharField(blank=True, max_length=2, null=True)),
                ('descrizione', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Deposito',
                'verbose_name_plural': 'Depositi',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Interesse',
                'verbose_name_plural': 'Interessi',
            },
        ),
        migrations.CreateModel(
            name='Mamma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Mamma',
                'verbose_name_plural': 'Mamme',
            },
        ),
        migrations.CreateModel(
            name='MeteoStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap', models.CharField(blank=True, max_length=5, null=True)),
                ('data_osservazione', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Meteo Store',
                'verbose_name_plural': 'Meteo Store',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Predizioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_destinazione', models.CharField(blank=True, max_length=2, null=True)),
                ('data_osservazione', models.DateField(auto_now_add=True)),
                ('cap', models.CharField(blank=True, max_length=5, null=True)),
                ('depo_abilitato', models.CharField(blank=True, max_length=2, null=True)),
                ('errore_anomalia', models.CharField(blank=True, max_length=2, null=True)),
                ('articoli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predizioni_articoli', to='nuova_app.articoli')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predizioni_deposito', to='nuova_app.deposito')),
            ],
            options={
                'verbose_name': 'Predizione',
                'verbose_name_plural': 'Predizioni',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(blank=True, max_length=1000, null=True)),
                ('bio', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Profilo',
                'verbose_name_plural': 'Profili',
            },
        ),
        migrations.CreateModel(
            name='Regione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'verbose_name': 'Regione',
                'verbose_name_plural': 'Regioni',
            },
        ),
        migrations.CreateModel(
            name='Uomo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuova_app.auto')),
            ],
            options={
                'verbose_name': 'Uomo',
                'verbose_name_plural': 'Uomini',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30, null=True)),
                ('deposito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verso_deposito', to='nuova_app.deposito')),
                ('regione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conn_regione', to='nuova_app.regione')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Province',
            },
        ),
        migrations.CreateModel(
            name='Predizioni_tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predizione_periodo', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('var_prezzo', models.CharField(blank=True, max_length=20, null=True)),
                ('qta', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('tipologia_marca', models.CharField(blank=True, max_length=255, null=True)),
                ('indicazione', models.FloatField(blank=True, null=True)),
                ('gg_consegna', models.IntegerField(blank=True, default=0, null=True)),
                ('prediz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predizionitab_predizioni', to='nuova_app.predizioni')),
            ],
            options={
                'verbose_name': 'Predizione_tab',
                'verbose_name_plural': 'Predizioni_tab',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=20)),
                ('interests', models.ManyToManyField(to='nuova_app.Interest')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Persone',
            },
        ),
        migrations.CreateModel(
            name='Ordinato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qta', models.IntegerField(blank=True, null=True)),
                ('dataconse', models.DateField(blank=True, null=True)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordinato_articolo', to='nuova_app.articoli')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordinato_deposito', to='nuova_app.deposito')),
            ],
            options={
                'verbose_name': 'Ordinato',
                'verbose_name_plural': 'Ordinati',
            },
        ),
        migrations.CreateModel(
            name='Meteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domani', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('settimana', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meteo_store', to='nuova_app.meteostore')),
            ],
            options={
                'verbose_name': 'Meteo',
                'verbose_name_plural': 'Meteo',
            },
        ),
        migrations.CreateModel(
            name='Indirizzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuova_app.city')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nuova_app.person')),
            ],
            options={
                'verbose_name': 'Indirizzo',
                'verbose_name_plural': 'Indirizzi',
            },
        ),
        migrations.CreateModel(
            name='Giacenze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ditta', models.DecimalField(decimal_places=0, default=1, max_digits=5)),
                ('codice', models.CharField(blank=True, max_length=25, null=True)),
                ('giacenza', models.IntegerField(blank=True, null=True)),
                ('impegnato_cliente', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('ordinato_fornitori', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('disponibilita', models.IntegerField(blank=True, null=True)),
                ('registration_date', models.DateField(auto_now=True)),
                ('articoli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giacenze_articoli', to='nuova_app.articoli')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giacenze_deposito', to='nuova_app.deposito')),
            ],
            options={
                'verbose_name': 'Giacenza',
                'verbose_name_plural': 'Giacenze',
            },
        ),
        migrations.CreateModel(
            name='DoctPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dottore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuova_app.doctor')),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuova_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Consegne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposito', models.CharField(blank=True, max_length=2, null=True)),
                ('provincia', models.CharField(blank=True, max_length=2, null=True)),
                ('cap', models.CharField(blank=True, max_length=5, null=True)),
                ('qta', models.IntegerField(blank=True, null=True)),
                ('data_consegne', models.DateField(blank=True, null=True)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consegne_articolo', to='nuova_app.articoli')),
                ('deposito_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consegne_deposito', to='nuova_app.deposito')),
            ],
            options={
                'verbose_name': 'Consegna',
                'verbose_name_plural': 'Consegne',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='nuova_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Bambino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('figlio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nuova_app.mamma')),
            ],
            options={
                'verbose_name': 'Bambino',
                'verbose_name_plural': 'Bambini',
            },
        ),
        migrations.AddField(
            model_name='articoli',
            name='depositi',
            field=models.ManyToManyField(through='nuova_app.Consegne', to='nuova_app.Deposito'),
        ),
    ]
