# Generated by Django 3.2.23 on 2024-03-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_auto_20240305_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genere',
            old_name='model',
            new_name='nome',
        ),
    ]
