# Generated by Django 3.2.23 on 2024-03-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuova_app', '0005_consegne'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consegne',
            options={},
        ),
    ]
