# Generated by Django 3.2.23 on 2024-03-14 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuova_app', '0006_alter_consegne_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consegne',
            options={'verbose_name': 'Consegna', 'verbose_name_plural': 'Consegne'},
        ),
    ]
