# Generated by Django 3.2.23 on 2024-03-17 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nuova_app', '0008_biglietto_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Esame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('voto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuova_app.studente')),
            ],
        ),
    ]
