# Generated by Django 3.2.23 on 2024-03-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuova_app', '0009_esame_studente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esame',
            name='voto',
            field=models.IntegerField(),
        ),
    ]
