# Generated by Django 3.2.23 on 2024-03-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuova_app', '0010_alter_esame_voto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biglietto',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='consegne',
            name='articolo',
        ),
        migrations.RemoveField(
            model_name='consegne',
            name='deposito',
        ),
        migrations.RemoveField(
            model_name='esame',
            name='studente',
        ),
        migrations.DeleteModel(
            name='Articoli',
        ),
        migrations.DeleteModel(
            name='Biglietto',
        ),
        migrations.DeleteModel(
            name='Consegne',
        ),
        migrations.DeleteModel(
            name='Deposito',
        ),
        migrations.DeleteModel(
            name='Esame',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Studente',
        ),
    ]
