# Generated by Django 3.2.23 on 2024-03-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anagrafica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30, null=True)),
                ('cognome', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Anagrafica',
                'verbose_name_plural': 'Anagrafiche',
            },
        ),
    ]
